# roles/k9s/meta/main.yml
galaxy_info:
  role_name: k9s
  author: Your Name
  description: Install K9s - Kubernetes CLI To Manage Your Clusters In Style
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - kubernetes
    - k8s
    - k9s
    - cli
    - devops

dependencies: []