---
# roles/jenkins/meta/main.yml
galaxy_info:
  author: Wahid Hamdi
  description: Installation de Jenkins avec Java
  company: ISET Tozeur
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 8
        - 9

dependencies: []